using QuNet

# println("-----Running maxpaths.jl-----")
# include("maxpaths.jl")
# println("-----Running percolations.jl-----")
# include("percolations.jl")
# println("-----Running gridsize.jl-----")
# include("gridsize.jl")
# println("-----Running userpairs.jl-----")
# include("userpairs.jl")
# println("-----Running timedepth.jl-----")
# include("timedepth.jl")
println("Running bandwidth_userpairs.jl")
include("new_bandwidth_userpairs.jl")
println("-----Running bandwidth_memory.jl")
include("new_bandwidth_memory.jl")
